Task7
aleksandr-zharov/nodejs-aws-backend pull request #5
Opened 2020-11-29 07:07 UTC by aleksandr-zharov

https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task7-lambda%2Bcognito-authorization/task.md

Task will be finally completed on Monday evening...

2020-12-01 12:35 UTC, NikaOrl requested changes
Good job! I have only one recommendation

2020-12-01 12:35 UTC, NikaOrl commented on authorization-service/handlers/basic-authorizer.ts
> +            Effect: process.env.PASSWORD === password && process.env.USER === username ? 'Allow' : 'Deny',
In case when you don't have 'PASSWORD' in 'process.env' and don't get a password from plainCreds you will get "Allow" effect. Because undefined === undefined.

Also according the task "This lambda should have at least **one environment variable with credentials: {yours_github_account_login}=TEST_PASSWORD**"

So in .env you should have sth like 
aleksandr-zharov=TEST_PASSWORD

And check it like 
`process.env[user] === password`

2020-12-01 13:23 UTC, NikaOrl commented
You have errors that doesn't allow to show products as a list 
![image](https://user-images.githubusercontent.com/29703381/100746121-57511a80-33f1-11eb-9d2e-3411a7b28754.png)

It should look like that 
![image](https://user-images.githubusercontent.com/29703381/100746223-7c458d80-33f1-11eb-80ce-35550ebff8ac.png)

2020-12-01 13:27 UTC, NikaOrl commented
Also I tested the adding of the products with following csv file:
"title","description","count","price","image"
"Product title1","description 1","1","11","1"
"Product title2","description 2","20","22","2"

And the products was not added. It's not a part of the ticket but it's better to check or attach required file format

2020-12-01 22:35 UTC, Anisotropic commented on authorization-service/handlers/basic-authorizer.ts
> +            Effect: process.env.PASSWORD === password && process.env.USER === username ? 'Allow' : 'Deny',
"at least one" means one or more) so two variables are ok)

2020-12-02 11:02 UTC, NikaOrl commented on authorization-service/handlers/basic-authorizer.ts
> +            Effect: process.env.PASSWORD === password && process.env.USER === username ? 'Allow' : 'Deny',
Yeah, "at least one variable **with credentials: {yours_github_account_login}=TEST_PASSWORD**" 
It means you can have **one or more** variables with credentials...

And I know what "at least one" means, thanks. I don't think that it's big mistake, just highlight what the task says

2020-12-02 21:16 UTC, agarmashevska commented
The products are not being added during testing

2020-12-06 18:22 UTC, merged